### PR TITLE
remove unneded chown commands in the entrypoint

### PR DESCRIPTION
**Pull request by besmirzanaj**
no need to chown the dirs for as long these are defined in the Dockerfile

### CODE REVIEW

**Comment by Jamesits** [comment]
There are two use cases where chown is required:
- If a user modifies `ATLAS_UID` or `ATLAS_GID`
- If a bind mount is used instead of a volume

However we could ignore the errors reported by chown, as I feel chown errors does not mean the program will definitely not be happy to run. If your specific deployment have issues on these chown commands but atlas can run without them, we can fix that.

**Comment by Jamesits** [comment]
I've guessed this happening. 

Could you please try if https://github.com/Jamesits/docker-ripe-atlas/commit/9db9093e72b438d2a5b07821335080c5361adf1f works for you? It still tries to chown but ignores the error.

**Comment by besmirzanaj** [comment]
Same error,

You have to add the same logic `|| true` also to line 19 and 20 of the entry point.

```
│ usermod: no changes                                                                                                                                               │
│ chown: changing ownership of '/var/atlas-probe/status': Invalid argument                                                                                          │
│ chown: changing ownership of '/var/atlas-probe/etc/probe_key': Read-only file system                                                                              │
│ chown: changing ownership of '/var/atlas-probe/etc/probe_key.pub': Read-only file system   
```

**Comment by Jamesits** [comment]
Sorry I missed two lines. Fixed now.

**Comment by besmirzanaj** [comment]
Looks good now. container is starting successfully.

**Comment by Jamesits** [comment]
Nice. I'll close this PR for now.

**Pull request closed without merging**
